# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gtk2-Ex-CellLayout-Base
version:      2
version_from: lib/Gtk2/Ex/CellLayout/Base.pm
installdirs:  site
requires:
    Gtk2:                          1.18
    List::Util:                    0
    Scalar::Util:                  0
    Scope::Guard:                  0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
